apiVersion: apps/v1 
kind: Deployment
metadata:
   name: petclinic 
#   annotations:
#      example-mutating-admission-webhook: "foo"
   labels:
     webhook: "true"
spec:
   replicas: 1 
   selector:
      matchLabels:
         app: petclinic
   template:
      metadata:
         labels:
            app: petclinic
      spec:
         containers:
         - name: petclinic
           image: egapm/springboot:petclinic-tomcat-openjdk8jre 
           ports:
           - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
   name: petclinic
spec:
   type: NodePort
   selector:
      app: petclinic 
   ports:
      - nodePort: 31319 
        port: 8080 
        targetPort: 8080

